packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@dha-team/arbundles': ^1.0.4
  '@types/kill-port': ^2.0.3
  arweave: ^1.15.7
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  html-minifier-terser: ^7.2.0
  kill-port: ^2.0.1
  nanoid: ^5.1.6
  open: ^10.2.0
  prettier: ^3.6.2
  terser: ^5.44.0

catalogs:
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.0.1
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.4
    tsx: ^4.20.5
    typescript: ^5.9.2
    vite: ^7.1.7
  inlined:
    '@antfu/utils': ^9.2.1
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.5.2

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
